#!/bin/sh

cd `dirname $0`

git submodule update --init --recursive 2>/dev/null

git pull
git submodule foreach git pull origin master

php ./server/admin/migrate/index.php


kto=`basename $HOME`
crontabfile=/tmp/crontab.$kto
crontab -l 2>/dev/null |grep -v "server/admin/" > $crontabfile 
pwd=`pwd`
app=`basename $pwd`

url="http://$kto.webkameleon.com/$app/server/admin/calendar/"
cmd="/usr/bin/wget -O /dev/null -q $url"
echo "*/20 * * * * $cmd" >> $crontabfile

url="http://$kto.webkameleon.com/$app/server/admin/purge/"
cmd="/usr/bin/wget -O /dev/null -q $url"
echo "5 * * * * $cmd" >> $crontabfile

url="http://$kto.webkameleon.com/$app/server/admin/payu/"
cmd="/usr/bin/wget -O /dev/null -q $url"
echo "15 * * * * $cmd" >> $crontabfile

url="http://$kto.webkameleon.com/$app/server/admin/afterdeadline/"
cmd="/usr/bin/wget -O /dev/null -q $url"
echo "*/30 * * * * $cmd" >> $crontabfile

crontab $crontabfile



if [ "`pwd|grep robson`" ]
then
    echo "Skoro Robson, to spadam"
    exit
fi

if [ ../../../robson/www/eat/Gruntfile.js -nt Gruntfile.js ]
then
    if [ "`pwd|grep pudel`" ]
    then
        cat ../../../robson/www/eat/Gruntfile.js |\
            sed "s/robson.webkameleon.com\/eat/pudel.webkameleon.com\/epapu/"|\
            sed "s/35729/35756/"|\
            sed "s/9000/9006/" > Gruntfile.js
    fi


    
fi
