#!/bin/sh

cd `dirname $0`

git submodule update --init --recursive 2>/dev/null

git pull
git submodule foreach git pull origin master

php ./server/admin/migrate/index.php


kto=`basename $HOME`


if [ "`pwd|grep robson`" ]
then
    echo "Skoro Robson, to spadam"
    exit
fi

if [ /home/robson/www/eat/Gruntfile.js -nt Gruntfile.js ]
then
    if [ "`pwd|grep pudel`" ]
    then
        cat /home/robson/www/eat/Gruntfile.js |\
            sed "s/robson.webkameleon.com\/eat/pudel.webkameleon.com\/epapu/"|\
            sed "s/35729/35756/"|\
            sed "s/9000/9006/" > Gruntfile.js
    fi


    if [ "`pwd|grep max`" ]
    then
        cat /home/robson/www/eat/Gruntfile.js |\
            sed "s/robson.webkameleon.com\/eat/pudel.webkameleon.com\/epapu/"|\
            sed "s/35729/35757/"|\
            sed "s/9000/9007/" > Gruntfile.js
    fi

    
fi
